packageExtensions:
  '@atls-ui-parts/layout@*':
    dependencies:
      csstype: '*'
  '@atls/webpack-proto-imports-loader@*':
    dependencies:
      webpack: '*'
  '@landing/index-page@*':
    dependencies:
        react-intl: '*'
  '@landing/state-action-page@*':
    dependencies:
        react-intl: '*'
  '@ui/link@*':
    dependencies:
        next: '*'
        react-dom: '*'   

yarnPath: .yarn/releases/yarn-0.0.1-git.20220426.hash-a30b37d.cjs
